### ISSUE TITLE
Password protect page

### ISSUE THREAD

**Issue by tscibilia** [chimpchimp/docker-manage-this-node#3]
I'm trying to figure out how to provide username/password protection on this page. The manage-this-node page says to pass environment variables in the config.json file. I'm not sure how to do that in this docker container. 

I tried using an -e BASIC_AUTH_USER & BASIC_AUTH_PASSWORD flags when running the initial container but that didn't work.

**Comment by chimpchimp** [comment]
You need to pass Docker each environment variable as its own argument. So it would be like this:

-e BASIC_AUTH_USER=user -e BASIC_AUTH_PASSWORD=password

Just tried it and it works as expected.
